### ISSUE TITLE
Some hashtags to add

### ISSUE THREAD

**Issue by datadave** [MiniCodeMonkey/harvey#3]
Part of the standbytaskforce -- I can help get the updated list

https://docs.google.com/spreadsheets/d/1XRQBrqR_SjEwUxLY3kOC9zdr643UU9ZT9dEdQwDwy5E/edit#gid=0

**Comment by MiniCodeMonkey** [comment]
Thanks for compiling and sharing this. I've updated the search filters based on the spreadsheet now: https://github.com/MiniCodeMonkey/harvey/commit/283bff94633217fb8340fd28bc59578e91f35367

Please note that there was a few hashtags that I had to leave out since they were a bit too generic, which would cause a lot of false positives (e.g. #orange)
